Spring:
    application:
        name: ecommercex
    datasource: 
        url: jdbc:mysql://localhost:3306/spring_ecommercedb?createDatabaseIfNotExist=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: ""
    jpa: 
        database: mysql    
        hibernate:
                ddl-auto: update